### ISSUE TITLE
 Find the Highest Altitude

### ISSUE THREAD

**Issue by prog-harsh** [prog-harsh/Hacktoberfest2022#11]
There is a biker going on a road trip. The road trip consists of n + 1 points at different altitudes. The biker starts his trip on point 0 with altitude equal 0.

You are given an integer array gain of length n where gain[i] is the net gain in altitude between points i​​​​​​ and i + 1 for all (0 <= i < n). Return the highest altitude of a point.

Example:

Input: gain = [-5,1,5,0,-7]
Output: 1
Explanation: The altitudes are [0,-5,-4,1,1,-6]. The highest is 1.

**Comment by adityawithdoublea** [comment]
Can you assign this issue to me?

**Comment by prog-harsh** [comment]
@adityawithdoublea sure
