### ISSUE TITLE
Container With Most Water [LeetCode]

### ISSUE THREAD

**Issue by prog-harsh** [prog-harsh/Hacktoberfest2022#12]
Given n non-negative integers a1, a2, ..., an , where each represents a point at coordinate (i, ai). n vertical lines are drawn such that the two endpoints of the line i is at (i, ai) and (i, 0). Find two lines, which, together with the x-axis forms a container, such that the container contains the most water.

Notice that you may not slant the container.

Example:

<img src="https://user-images.githubusercontent.com/62786689/137006754-f5368e7f-b9aa-43f2-9d9e-34b6b8153122.png " width="500" height="250" />

Input: height = [1,8,6,2,5,4,8,3,7]
Output: 49
Explanation: The above vertical lines are represented by array [1,8,6,2,5,4,8,3,7]. In this case, the max area of water (blue section) the container can contain is 49.

**Comment by ArchanJS** [comment]
@prog-harsh Hello, Can I get assigned? Thank you in advance.

**Comment by ArchanJS** [comment]
@prog-harsh  I have made a PR #16 . Please check.
