### ISSUE TITLE
Number guessing game using JavaScript

### ISSUE THREAD

**Issue by prog-harsh** [prog-harsh/Hacktoberfest2022#140]
Build a number guessing game. There would be limited amount of chance for guessing the number. Try to make front-end also using HTML and CSS.
Make a separate folder named as "Number Guess"

**Comment by RadhikaChhabra17** [comment]
Hi, I would like to contribute to this issue. Can you assign this to me?

**Comment by shivansh12032004** [comment]
Hey, can you assign this issue to me?

**Comment by palaksv** [comment]
Please assign this issue to me.

**Comment by theutpal01** [comment]
please assign it to me
