### ISSUE TITLE
Check if a subarray with 0 sum exists or not

### ISSUE THREAD

**Issue by prog-harsh** [prog-harsh/Hacktoberfest2022#46]
Given an integer array, check if it contains a subarray having zero-sum.

For example:

Input:  { 3, 4, -7, 3, 1, 3, 1, -4, -2, -2 }
 
Output: Subarray with zero-sum exists
 
The subarrays with a sum of 0 are:
 
{ 3, 4, -7 }
{ 4, -7, 3 }
{ -7, 3, 1, 3 }
{ 3, 1, -4 }
{ 3, 1, 3, 1, -4, -2, -2 }
{ 3, 4, -7, 3, 1, 3, 1, -4, -2, -2 }

**Comment by sunidhisachan** [comment]
@prog-harsh I can try this.

**Comment by prog-harsh** [comment]
@sunidhisachan anyone can do the PR there is no limitations with the number of assignee's.

**Comment by hnifmaghfur** [comment]
I already make PR #68 in javascript can you check and MR it, please.
